### ISSUE TITLE
Add command to download latest types file and some debug comamnds

### ISSUE THREAD

**Issue by JohnnyMorganz** [HawDevelopment/Vscode-Luau-Analyzer#3]
It would be great if there was a command to download the `globalTypes.d.lua` file into the current working directory through the extension, rather than having to manually do it (example in my fork: https://github.com/JohnnyMorganz/Vscode-Luau-Analyzer/blob/master/src/extension.ts#L29-L55)

It would also be nice if the debug commands I added to my fork could also be added, namely the ability to dump the current source map using `--dump-source-map`, and view the annotated version of the file when passing `--annotate` (example: https://github.com/JohnnyMorganz/Vscode-Luau-Analyzer/blob/master/src/extension.ts#L57-L75)

Note that the versions I wrote in my fork *work* but I did just hacked them together, you may want to do it differently.

**Comment by HawDevelopment** [comment]
Implemented in commits: 23a373fccdc581384473cabbb38aa1459ddca883 and 60c83f2486a1092bd1e86f2d99e7e88a985a001a
