### ISSUE TITLE
Use VSCode settings to manage rojo project path and types path

### ISSUE THREAD

**Issue by JohnnyMorganz** [HawDevelopment/Vscode-Luau-Analyzer#4]
It would be better if the `setRojoProject` and `setTypeDefsPath` commands were instead converted to proper vscode configurations.
Also, they should have defaults set to `default.project.json` and `globalTypes.d.lua` respectively so that a user does not need to manually set these if when getting started in a standard project
https://github.com/JohnnyMorganz/Vscode-Luau-Analyzer/blob/master/package.json#L21-L30

**Comment by HawDevelopment** [comment]
Implemented in #8
