### ISSUE TITLE
Show diagnostics for more than just the current file

### ISSUE THREAD

**Issue by JohnnyMorganz** [HawDevelopment/Vscode-Luau-Analyzer#5]
Currently, the extension only shows diagnostics for the current file (https://github.com/HawDevelopment/Vscode-Luau-Analyzer/blob/master/src/FileAnalyzer.ts#L47-L49), and ignores any diagnostics sent by the luau-analyze tool about other files (these are normally generated for required files).

It might be nice to also show diagnostics on required files (potentially behind a setting to do this)

**Comment by HawDevelopment** [comment]
Implemented in commit: f81f14ce70ed21efdb283bb9194339be78907704
