### ISSUE TITLE
Arguments for luau-analyze-rojo wrong / luau-analyze-rojo stdin not working

### ISSUE THREAD

**Issue by Corecii** [HawDevelopment/Vscode-Luau-Analyzer#9]
This extension was giving me no diagnostics so I added a log for the command it was trying to use:

`luau-analyze --formatter=plain - --stdin-filepath=src/lib/Storage/UpdateRoot.lua --project=rojo-packaged.project.json --defs=globalTypes.d.lua`

If I run this manually, it says:

`Cannot get "-": path does not exist`

---

I tried to fix this by only removing the `-`, and I got no output.

Ultimately I ended up providing the filepath after all of the arguments:

`luau-analyze --formatter=plain --project=rojo-packaged.project.json --defs=globalTypes.d.lua src/lib/Storage/UpdateRoot.lua`

This worked fine! I'm not sure if my set up is different from others or what, but `luau-analyze-rojo` works *only* if a folder or file is provided as one of the arguments.

**Comment by Corecii** [comment]
Ah, I think I understand how this was *suppose to* work: it was suppose to take in the current file from `stdin`, right? For some reason that doesn't work for me on the most recent version of `luau-analyze-rojo`.

**Comment by HawDevelopment** [comment]
Are you using the latest extension and `lua-analyze-rojo` version? It works for me.
![image](https://user-images.githubusercontent.com/70876593/161737385-38eea983-bcda-4c84-a1dc-293a88233183.png)

**Comment by Kampfkarren** [comment]
I compiled luau-analyze-rojo from source and am getting this bug.

**Comment by JohnnyMorganz** [comment]
This is a bug with luau-analyze-rojo in its most recent update, I can quickly push a patch for this

**Comment by Corecii** [comment]
I'm not longer having problems with this.
